# era-mb-game.igroteh.su — мобильная игра «Эра перемен» (era_mobile_api)
# HTTP: ACME-челлендж + редирект на HTTPS

server {
    listen 80;
    listen [::]:80;
    server_name era-mb-game.igroteh.su;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        allow all;
        try_files $uri =404;
        access_log off;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
